apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joke-service
  template:
    metadata:
      labels:
        app: joke-service
    spec:
      containers:
      - name: joke-service
        image: siutex/devops:joke_service
        ports:
        - containerPort: 5000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
