name: 'eks_infra'

on:
    workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 0.14.10
  TF_WORKING_DIR: 'terraform'
  APP_WORKING_DIR: 'kubernetes'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: 'SSH Key Setup'
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keygen -y -f $HOME/.ssh/id_rsa > $HOME/.ssh/id_rsa.pub
        echo "PUBLIC_KEY=$(cat $HOME/.ssh/id_rsa.pub)" >> $GITHUB_ENV

    - name: Terraform Format
      run: terraform fmt -check
      
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color
      env:
        TF_VAR_public_key: ${{ env.PUBLIC_KEY }}
    - name: Install jq
      run: sudo apt-get install jq

    - name: Terraform Apply
      id: terraform
      run: |
        terraform apply -auto-approve
        cluster_name_value=$(terraform output -raw cluster_name)
        aws secretsmanager update-secret --secret-id cluster_name --secret-string "$cluster_name_value"
      env:
        TF_VAR_public_key: ${{ env.PUBLIC_KEY }}
        
    - name: Configure kubectl
      run: |
        aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name my-cluster
      
    - name: Verify the cluster  
      run: |
       kubectl cluster-info
       kubectl get nodes
      env:
        TF_VAR_public_key: ${{ env.PUBLIC_KEY }}






